Removed "What's next" option (in preferences and all)
Team-MCToolkit/MCToolkit pull request #127
Opened 2020-12-01 17:34 UTC by Max094Reikeb

This PR removes the "What's next" that appears when we create a workspace, and removes its option.

2020-12-01 17:46 UTC, ShockingArtist commented
I suggest instead of removing the MCreator what's next page, we should make an MCtoolkit version of it in the Mctoolkit website, and link to that page.

2020-12-01 17:48 UTC, Goldorion approved these changes

2020-12-01 18:07 UTC, Max094Reikeb commented
> I suggest instead of removing the MCreator what's next page, we should make an MCtoolkit version of it in the Mctoolkit website, and link to that page.

The team already decided not to.

2020-12-01 18:17 UTC, ShockingArtist commented
oh

2020-12-01 18:22 UTC, NOYBss requested changes
If the boolean `showWebsite` in method WorkspaceGeneratorSetupDialog#runSetup is only used for openning the website, argument must be removed from the method since there is no use/need.

2020-12-01 18:22 UTC, NOYBss commented on src/main/java/net/mcreator/ui/MCreator.java
> -
I believe this shouldn't be removed. Looks like it is running some kind of setup.

2020-12-01 20:06 UTC, Max094Reikeb commented on src/main/java/net/mcreator/ui/MCreator.java
> -
Are you sure? Because the only setup it seems to run is opening your browser's page with the link of the page. I tried the code while creating a new workspace and everything works fine for me...

2020-12-02 05:50 UTC, NOYBss commented on src/main/java/net/mcreator/ui/MCreator.java
> -
The method is not just for openning the website, it may have worked, but it may be used somewhere else. Just in case, 
I recommend you to just remove the `showWebsite` argument from the method, and keep this part of code.

2020-12-02 07:25 UTC, Max094Reikeb commented on src/main/java/net/mcreator/ui/MCreator.java
> -
The code `WorkspaceGeneratorSetupDialog.runSetup(this, PreferencesManager.PREFERENCES.notification.openWhatsNextPage);` is only used to open the "What's next" page if activated in preferences. Because there is nothing else in the `if (WorkspaceGeneratorSetup.shouldSetupBeRan(workspace.getGenerator()))`, I can delete the whole `if` thing. So it works.

2020-12-02 07:27 UTC, merged