Modified Potion effect mod element
Team-MCToolkit/MCToolkit pull request #138
Opened 2020-12-04 09:27 UTC by Max094Reikeb

This PR modifies the Potion Effect mod element (among with other small stuff)
- Modified some strings
- Modified run configurations in IDEA (replaced `MCreator` by `MCToolkit`)

2020-12-04 12:48 UTC, Goldorion commented on src/main/java/net/mcreator/element/ModElementType.java
> +	@SerializedName("potioneffect") POTIONEFFECT(BaseType.POTIONEFFECT, RecipeElementType.NONE),
Never change a mod element id, except if you have a working converter. All workspaces will broke if you don’t make a converter. I already tried to make one, but it seems to be more difficult than a normal converter.

2020-12-04 12:58 UTC, Max094Reikeb commented on src/main/java/net/mcreator/element/ModElementType.java
> +	@SerializedName("potioneffect") POTIONEFFECT(BaseType.POTIONEFFECT, RecipeElementType.NONE),
Fixed!

2020-12-04 17:14 UTC, Max094Reikeb commented
> Rechange the definition files. Currently, these definition files are applied for a mod element with "potionitem" as ID.

What definition files?

2020-12-04 21:12 UTC, Goldorion commented
> > Rechange the definition files. Currently, these definition files are applied for a mod element with "potionitem" as ID.
> 
> What definition files?

id.definition.yaml

2020-12-04 22:11 UTC, Max094Reikeb commented
> Rechange the definition files. Currently, these definition files are applied for a mod element with "potionitem" as ID.

Fixed!

2020-12-05 00:07 UTC, Goldorion commented on plugins/generator-1.15.2/forge-1.15.2/templates/potionitem.java.ftl
> +			new EffectInstance(${effect.effect?replace("Effect.effect", "PotionEffect.potion")}, ${effect.duration}, ${effect.amplifier})<#if effect?has_next>,</#if>
It should be `${effect.effect?replace("PotionEffect.effect", ".potion")}` instead of `${effect.effect?replace("Effect.effect", "PotionEffect.potion")}`

2020-12-05 00:10 UTC, Goldorion requested changes

2020-12-05 00:10 UTC, Goldorion commented on plugins/generator-1.16.4/forge-1.16.4/templates/potionitem.java.ftl
> +			new EffectInstance(${effect.effect?replace("Effect.effect", ".potion")?replace("Potion.potion", "PotionEffect.potion")}, ${effect.duration}, ${effect.amplifier})<#if effect?has_next>,</#if>
Same thing here

2020-12-05 00:10 UTC, Goldorion commented on plugins/mcreator-localization/lang/texts.properties
> +modelement.potioneffect=Potion Effect
Change potioneffect for potion as it's the ID

2020-12-05 00:10 UTC, Goldorion commented on plugins/mcreator-localization/lang/texts.properties
> +modelement.potioneffect.description=Potion effect is an effect that can be given to entities.
Same thing here

2020-12-05 00:10 UTC, Goldorion commented on plugins/mcreator-localization/lang/texts.properties
> +elementgui.potioneffect.is_instant=Is instant
Same thing for lines #1763 to 1779.

2020-12-05 00:12 UTC, Max094Reikeb commented on plugins/mcreator-localization/lang/texts.properties
> +modelement.potioneffect=Potion Effect
It's not important it's just a key name it won't affect anything

2020-12-05 00:13 UTC, Goldorion commented on plugins/mcreator-localization/lang/texts.properties
> +modelement.potioneffect=Potion Effect
Not this one. For the name and the description of mod element, it has to be `modelement.*modElementId*`.

2020-12-05 00:14 UTC, Max094Reikeb commented on plugins/mcreator-localization/lang/texts.properties
> +modelement.potioneffect=Potion Effect
You're right indeed, but for the other ones, not important.

2020-12-05 00:16 UTC, Goldorion commented on plugins/mcreator-localization/lang/texts.properties
> +modelement.potioneffect=Potion Effect
This one and the next have to be changed only. Sorry

2020-12-05 01:40 UTC, Max094Reikeb commented on plugins/generator-1.16.4/forge-1.16.4/templates/potionitem.java.ftl
> +			new EffectInstance(${effect.effect?replace("Effect.effect", ".potion")?replace("Potion.potion", "PotionEffect.potion")}, ${effect.duration}, ${effect.amplifier})<#if effect?has_next>,</#if>
Wdym by "same thing"? There isn't `${effect.effect?replace("Effect.effect", "PotionEffect.potion")}` here

2020-12-05 01:43 UTC, Max094Reikeb commented on plugins/generator-1.15.2/forge-1.15.2/templates/potionitem.java.ftl
> +			new EffectInstance(${effect.effect?replace("Effect.effect", "PotionEffect.potion")}, ${effect.duration}, ${effect.amplifier})<#if effect?has_next>,</#if>
Fixed!

2020-12-05 01:44 UTC, Max094Reikeb commented on plugins/generator-1.16.4/forge-1.16.4/templates/potionitem.java.ftl
> +			new EffectInstance(${effect.effect?replace("Effect.effect", ".potion")?replace("Potion.potion", "PotionEffect.potion")}, ${effect.duration}, ${effect.amplifier})<#if effect?has_next>,</#if>
Fixed!

2020-12-05 01:44 UTC, Max094Reikeb commented on plugins/mcreator-localization/lang/texts.properties
> +modelement.potioneffect=Potion Effect
Fixed!

2020-12-05 01:44 UTC, Max094Reikeb commented on plugins/mcreator-localization/lang/texts.properties
> +modelement.potioneffect.description=Potion effect is an effect that can be given to entities.
Fixed!

2020-12-05 03:34 UTC, Goldorion approved these changes

2020-12-05 17:28 UTC, merged