Modify Potion Effect and Potion Item mod elements previews
Team-MCToolkit/MCToolkit pull request #153
Opened 2020-12-07 23:35 UTC by Max094Reikeb

This PR modifies Potion Effect and Potion Item previews.
- Potion Effect has the same preview as its mod element icon
- Potion Item has a bottle as a preview, filled with the liquid with its potion effect color.

2021-01-11 14:37 UTC, Goldorion commented on src/main/java/net/mcreator/element/types/PotionEffect.java
> -	@Override public BufferedImage generateModElementPicture() {
Use the texture the user selected. It will be better than only the default image. Check the Item class to see how to do it.

2021-01-13 15:57 UTC, Goldorion requested changes
You need to change the path f the texture inside the code file too. Currently, Forge/Minecraft will search the effect icon inside "assets/modid/textures/others(or the old path)".

2021-01-13 15:59 UTC, Goldorion commented on plugins/generator-resourcepack-1.16.x/resourcepack-1.16.x/generator.yaml
> +mob_effect_textures_dir: "@MODASSETSROOT/textures/others/mob_effect"
Also, this is not the correct path for the resource pack. It has to be "textures/mob_effect".

2021-01-13 16:24 UTC, Max094Reikeb commented on plugins/generator-resourcepack-1.16.x/resourcepack-1.16.x/generator.yaml
> +mob_effect_textures_dir: "@MODASSETSROOT/textures/others/mob_effect"
When I create a potion effect, the icon saved under `textures/others/mob_effect`

2021-01-13 16:40 UTC, Goldorion commented on plugins/generator-resourcepack-1.16.x/resourcepack-1.16.x/generator.yaml
> +mob_effect_textures_dir: "@MODASSETSROOT/textures/others/mob_effect"
It's saved there because you told to MCreator to save it there. However, Minecraft only checks the mob_effect folder inside the main textures folder, so if you put the folder inside the "others" folder, Minecraft will not see textures. So, you have to change "textures/others/mob_effect" for "textures/mob_effect".

2021-01-13 18:02 UTC, Goldorion commented on plugins/generator-resourcepack-1.16.x/resourcepack-1.16.x/generator.yaml
> +mob_effect_textures_dir: "@MODASSETSROOT/textures/others/mob_effect"
I'm only talking about the resource pack generator. You can keep what you did for the other ones.

2021-01-14 17:26 UTC, Max094Reikeb commented
@Goldorion I can merge now?

2021-01-14 17:29 UTC, Goldorion approved these changes
It looks good for me, but we should wait a second review.

2021-01-23 17:21 UTC, merged