Port item modifications to 1.16.4
Team-MCToolkit/MCToolkit pull request #169
Opened 2020-12-12 16:23 UTC by Max094Reikeb

This procedure ports item modifications to 1.16.4.
- Dispense behavior from #19
- New blockly tooltip support from #93

2020-12-12 19:16 UTC, NOYBss requested changes
This should fix the crash. Looks like mojang added methods for setting/getting.

2020-12-12 19:16 UTC, NOYBss commented on plugins/generator-1.16.4/forge-1.16.4/templates/item.java.ftl
> +					boolean success = this.successful;
```suggestion
				this.setSuccessful(<@procedureOBJToConditionCode data.dispenseSuccessCondition/>);

				<#if hasProcedure(data.dispenseResultItemstack)>
					boolean success = this.isSuccessful();

```

2020-12-12 20:03 UTC, Max094Reikeb commented on plugins/generator-1.16.4/forge-1.16.4/templates/item.java.ftl
> +					boolean success = this.successful;
Done, but I think there is another error...

2020-12-12 20:39 UTC, NOYBss requested changes

2020-12-12 20:39 UTC, NOYBss commented on plugins/generator-1.16.4/forge-1.16.4/templates/item.java.ftl
> +				this.successful = <@procedureOBJToConditionCode data.dispenseSuccessCondition/>;
```suggestion
				this.setSuccessful(<@procedureOBJToConditionCode data.dispenseSuccessCondition/>);
```
You forgot this part 😄

2020-12-12 21:21 UTC, Max094Reikeb commented on plugins/generator-1.16.4/forge-1.16.4/templates/item.java.ftl
> +				this.successful = <@procedureOBJToConditionCode data.dispenseSuccessCondition/>;
Done!

2020-12-12 22:02 UTC, NOYBss requested changes
I didn't see this either 😅

2020-12-12 22:02 UTC, NOYBss commented on plugins/generator-1.16.4/forge-1.16.4/templates/item.java.ftl
> +				this.successful = true;
```suggestion
				this.setSuccessful(true);
```
I didn't see this either 😅

2020-12-12 22:14 UTC, Max094Reikeb commented on plugins/generator-1.16.4/forge-1.16.4/templates/item.java.ftl
> +				this.successful = true;
Done!

2020-12-12 22:19 UTC, NOYBss commented
Queues takes forever... Anyways I don't see any other direct access to `successful` boolean

2020-12-12 23:44 UTC, AlsoSomeoneElse commented
Seems good, but rather than edit the procedures.java.ftl file here too, I think it'd be better to wait for #131 to get approved instead

2020-12-13 00:12 UTC, NOYBss approved these changes
Looks good now, but 2 pr's adding same stuff will conflict (even though its the same thing). So when the first pr gets merged, second must resolve the conflicts.

2020-12-13 00:13 UTC, Max094Reikeb commented
> Looks good now, but 2 pr's adding same stuff will conflict (even though its the same thing). So when the first pr gets merged, second must resolve the conflicts.

Yes I know

2020-12-13 00:25 UTC, NOYBss commented
`procedureToRetvalCode` and `procedureToRetvalCodeTwo` are the same thing, there is only name difference, whats two for?

2020-12-13 00:27 UTC, Max094Reikeb commented
> `procedureToRetvalCode` and `procedureToRetvalCodeTwo` are the same thing, there is only name difference, whats two for?

Let it go, I'm deleting my changes anyways. The last commit of @AlsoSomeoneElse added everything I needed so I'm gonna revert my changes.

2020-12-13 01:50 UTC, merged