Code rewritefor creating mod elements
Team-MCToolkit/MCToolkit pull request #185
Opened 2020-12-23 06:27 UTC by Goldorion

This PR changes the code to create new mod elements. Mod elements are still registered with the Map variable. It's the first step for custom mod elements in plugins as we will now be able to create new mod elements without coding them with the other ones.

Changelog:
* Re-created ModElementType as a class
* Change each `@SerializableName` for a ModElementType variable
* Adapted the constructor to use all old things
* Added a second constructor for mod elements using a different registry name and name (e.g used for localizations)
* Move everything related to the definition and the registry of mod elements to a new subpackage (`registry`)
* Separated `BaseType` and `RecipeElementType` enums of `ModElementType`

Note: As this PR changes a lot of things in the code, it can be a breaking PR, so please test with multiple workspaces (create new workspaces and test with your old ones). Creative tab, Ranged item and Potion mod elements should be more tested.

2020-12-23 12:08 UTC, Max094Reikeb commented
Well, build errors so...

2020-12-26 02:10 UTC, Max094Reikeb commented
Why did you add log file? (`log/latest.log`)

2020-12-26 02:18 UTC, Goldorion commented
> 
> 
> Why did you add log file? (`log/latest.log`)

Because Intellij is stupid.

2020-12-26 06:21 UTC, NOYBss requested changes
PR looks good overall, I marked somewhere you could improve and reduce the amount of code.
I just want to ask why did you changed the switch statement in `integration/TestWorkspaceDataProvider` to a if statement?

2020-12-26 06:21 UTC, NOYBss commented on src/main/java/net/mcreator/element/registry/ModElementType.java
> +		ModElementTypeRegistry.elements.add(this);
```suggestion
		this(registryName, registryName, baseType, recipeElementType)
```

2020-12-26 06:27 UTC, Goldorion commented
> 
> 
> I just want to ask why did you changed the switch statement in `integration/TestWorkspaceDataProvider` to an if statement?

The switch statement didn't seem to work.

2020-12-26 07:00 UTC, NOYBss reviewed
I'll just commit this, I always forgot `;` 😄

2020-12-26 07:10 UTC, NOYBss approved these changes

2020-12-26 15:07 UTC, Max094Reikeb requested changes
The log file is still there...

2020-12-26 15:07 UTC, Max094Reikeb commented on .gitignore
> +**/.logs/latest.log
There is no `.` in front of the `logs` because the folder isn't `.logs` but `logs`

2020-12-26 15:18 UTC, Goldorion commented on .gitignore
> +**/.logs/latest.log
Oh yes sorry.

2020-12-26 15:21 UTC, Max094Reikeb approved these changes
Should be good, but wait for 3rd approval before merging...

2020-12-27 17:48 UTC, Max094Reikeb commented on .gitignore
> +**/logs/latest.log
I don't get it, where do you add this line? On this PR or on your latest one?

2020-12-27 18:04 UTC, Goldorion commented on .gitignore
> +**/logs/latest.log
I added it on this PR before adding it to the latest one.

2020-12-27 18:08 UTC, Max094Reikeb approved these changes
Sounds good.

2020-12-28 12:06 UTC, AlsoSomeoneElse commented
Tested it for a bit and didn't get any issue, but I'll try to test it some more

2020-12-31 17:42 UTC, AlsoSomeoneElse requested changes
You'll also have to fix the conflicts

2020-12-31 17:42 UTC, AlsoSomeoneElse commented on src/main/java/net/mcreator/element/registry/ModElementType.java
> +	public static final ModElementType ACHIEVEMENT = new ModElementType("achievement", BaseType.ACHIEVEMENT, RecipeElementType.BLOCK);
The RecipeElementType should be NONE

2020-12-31 17:42 UTC, AlsoSomeoneElse commented on src/main/java/net/mcreator/element/registry/ModElementType.java
> +			if(me.name.equals(modElementName)){
This should check `registryName` instead of `name`

2020-12-31 17:42 UTC, AlsoSomeoneElse commented on src/main/java/net/mcreator/element/registry/ModElementTypeRegistry.java
> +import net.mcreator.element.registry.ModElementType;
This import can be removed

2020-12-31 17:42 UTC, AlsoSomeoneElse commented on src/main/java/net/mcreator/workspace/elements/ModElement.java
> +		this.type = type.name();
This should get the registry name instead

2020-12-31 17:42 UTC, AlsoSomeoneElse commented on src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
> +		} else if (modElement.getType().equals(ModElementType.RANGEDITEM.getRegistryName())) {
This should have `ModElementType.RANGEDITEM.equals(modElement.getType())` as the condition

2020-12-31 17:42 UTC, AlsoSomeoneElse commented on src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
> +		} else if (ModElementType.POTIONEFFECT.getRegistryName().equals(modElement.getType())) {
This should have `ModElementType.POTIONEFFECT.equals(modElement.getType())` as the condition

2020-12-31 17:46 UTC, Goldorion commented
> 
> 
> You'll also have to fix the conflicts

I will fix conflicts just before we merge the PR.

2021-01-14 17:33 UTC, Max094Reikeb commented
Please keep it as a draft as this PR won't be merged until MCreator is over.

2021-01-14 17:36 UTC, Goldorion commented
I tried to fix all conflicts, but some files (mainly files used for tests) had a lot of things, so I maybe did wrong things.

> 
> 
> Please keep it as a draft as this PR won't be merged until MCreator is over.

There is the merge later label, but ok.

2021-01-14 17:42 UTC, Max094Reikeb requested changes

2021-01-14 17:42 UTC, Max094Reikeb commented on src/main/java/net/mcreator/element/registry/ModElementTypeRegistry.java
> +		put(ModElementType.POTIONITEM, new ModTypeRegistration<>(null, "potionitem", PotionItemGUI::new, PotionItem.class));
You forgot to add Gamerule mod element here.

2021-01-14 17:55 UTC, Goldorion commented on src/main/java/net/mcreator/element/registry/ModElementTypeRegistry.java
> +		put(ModElementType.POTIONITEM, new ModTypeRegistration<>(null, "potionitem", PotionItemGUI::new, PotionItem.class));
Fixed, but I think the ion is missing.

2021-01-14 17:56 UTC, Max094Reikeb commented on src/main/java/net/mcreator/element/registry/ModElementTypeRegistry.java
> +		put(ModElementType.POTIONITEM, new ModTypeRegistration<>(null, "potionitem", PotionItemGUI::new, PotionItem.class));
The icon isn't missing, I fixed stuff myself.

2021-06-13 01:32 UTC, closed without merging