"Dispense behavior" options for items
Team-MCToolkit/MCToolkit pull request #19
Opened 2020-11-04 18:39 UTC by AlsoSomeoneElse

This PR adds some options to specify the dispense behavior of an item, whether it's dispensed successfully, and what item it becomes after being dispensed. It includes three procedure templates specifically to damage/consume/change the item after being dispensed.

This PR also adds support for itemstack procedure selectors, and procedures with a return value can now pass any amount of dependencies (they caused compilation errors if more than 5 were passed).

2020-11-04 19:58 UTC, Max094Reikeb commented
Looks like you got a problem...
<img width="908" alt="Capture d’écran 2020-11-04 à 20 58 01" src="https://user-images.githubusercontent.com/49318596/98161695-76d35100-1ee0-11eb-9ab4-31bb04b30b3a.png">

2020-11-04 20:03 UTC, Max094Reikeb requested changes
There's a bug (as said earlier) to be fixed!

2020-11-04 20:03 UTC, Max094Reikeb commented on src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
> +			item.dispenseResultItemstack = new Procedure("itemstack1");
There's something wrong with those lines, check my previous comment to see the error.

2020-11-04 20:16 UTC, Defeatomizer commented
>This PR also adds support for itemstack prpcedure selectors

This is actually already supported by MCreator.

2020-11-05 08:45 UTC, Max094Reikeb commented
It looks like your problem is still there...

2020-11-05 16:53 UTC, Max094Reikeb approved these changes
Sounds good!

2020-11-07 21:17 UTC, Goldorion approved these changes

2020-11-07 21:18 UTC, Goldorion commented
It seems to be ok. Also, will you be able to add this feature for the food mod element as it also extends to the Item class?

2020-11-08 09:49 UTC, merged