New reosurce features + Resource pack generator
Team-MCToolkit/MCToolkit pull request #2
Opened 2020-10-31 16:49 UTC by Goldorion

This PR adds:
- Added custom directories for sounds and textures
- Added new texture categories: entities and paintings (texture has to be re-selected for all paintings)
- Added a resource pack generator

2020-10-31 22:46 UTC, Max094Reikeb requested changes
Just look at my comments.

2020-10-31 22:46 UTC, Max094Reikeb commented on plugins/mcreator-localization/lang/texts.properties
> +elementgui.music_disc.event_crafted_smelted=When item is crafted/smelted
No need for this key, the key `elementgui.common.event_on_crafted` already exists for the text "When item is crafted/smelted"

2020-10-31 22:46 UTC, Max094Reikeb commented on plugins/mcreator-localization/lang/texts.properties
> +elementgui.tool.event_crafted=When item is crafted/smelted
Same there, a common key already exists

2020-10-31 22:46 UTC, Max094Reikeb commented on src/main/java/net/mcreator/element/GeneratableElement.java
> +	public static final transient int formatVersion = 15;
Why are you directly moving from 13 to 15?

2020-10-31 22:49 UTC, Goldorion commented on src/main/java/net/mcreator/element/GeneratableElement.java
> +	public static final transient int formatVersion = 15;
Because it won't be in the 2020.5, and 14 is already taken.

2020-10-31 22:50 UTC, Goldorion commented on plugins/mcreator-localization/lang/texts.properties
> +elementgui.music_disc.event_crafted_smelted=When item is crafted/smelted
I think I just need to add new commits in this branch.

2020-11-01 12:47 UTC, Max094Reikeb commented
Looks like you have a key problem
<img width="884" alt="Capture d’écran 2020-11-01 à 13 46 44" src="https://user-images.githubusercontent.com/49318596/97803194-c3046400-1c48-11eb-9c62-c32dffdd10f3.png">

2020-11-01 12:51 UTC, Max094Reikeb requested changes
My comment deals with your key problem I just showed you just above

2020-11-01 12:51 UTC, Max094Reikeb commented on plugins/mcreator-localization/lang/texts.properties
> +elementgui.tool.event_crafted=When item is crafted/smelted
You don't need the key `elementgui.tool.event_crafted` because the text "When item is crafted/smelted" is already common. (`elementgui.common.event_on_crafted`) and also, you deleted the key `elementgui.tool.event_block_destroyed`, why did you do that?

2020-11-01 14:30 UTC, Defeatomizer commented on src/main/java/net/mcreator/element/GeneratableElement.java
> +	public static final transient int formatVersion = 15;
>14 is already taken.
Are you talking about MCreator#436?

2020-11-03 03:15 UTC, Goldorion commented on plugins/mcreator-localization/lang/texts.properties
> +elementgui.tool.event_crafted=When item is crafted/smelted
I didn't delete myself. I had some problems with other branches after I merged new commits of MCreator.

2020-11-03 07:26 UTC, Max094Reikeb approved these changes
Sounds good! We should wait for at least one people to review and approve this.

2020-11-03 12:13 UTC, Blackout03 approved these changes
Looks good to me

2020-11-03 12:15 UTC, merged