Added support for Time variable and dependency
Team-MCToolkit/MCToolkit pull request #201
Opened 2020-12-29 03:36 UTC by Goldorion

This PR adds a new variable and dependency type, Time. This new variable type also adds some new getter to be able to use methods of the Date class (it adds my Date plugin with the official way). As this new variable is not a big one and doesn't have a reason to be used as a Global variable, I only added it for local variables. Also, if it's added to GV, I'm not sure if it will have good support.

Note: Procedure blocks are implemented in JSON as it's much more simple to make, but they use an input value to get a Time variable (with a normal getter or a getter from another procedure (maybe other PBs in the future)). Basic procedure blocks like the variable getter, setter and return value are, however, implemented in the code like the other ones.

2020-12-29 13:08 UTC, NOYBss requested changes
Typo 😄

2020-12-29 13:08 UTC, NOYBss commented on plugins/generator-1.15.2/forge-1.15.2/procedures/_set_variable.java.ftl
> +        ${name} =(DATE)${value};
```suggestion
        ${name} =(Date)${value};
```

2020-12-29 13:09 UTC, NOYBss commented
Btw do you really need to cast to Date in _set_variable procedure block?

2020-12-29 22:36 UTC, AlsoSomeoneElse requested changes

2020-12-29 22:36 UTC, AlsoSomeoneElse commented on src/main/resources/blockly/js/mcreator_blocks.js
> +        this.setOutput(true, 'MCItemBlock');
This should be 'Time'

2020-12-29 23:54 UTC, Goldorion commented
> 
> 
> Btw do you really need to cast to Date in _set_variable procedure block?

For most of the cases, surely not, but it can prevent some build errors, so we can keep it. It's not like if it changes something.

2020-12-30 00:20 UTC, Max094Reikeb approved these changes
Sounds good. Does this PR close #71 ? Because if it does, you should add the close keyword.

2020-12-30 00:21 UTC, Goldorion commented
> 
> 
> Sounds good. Does this PR close #71 ? Because if it does, you should add the close keyword.

Oh yes, it closes the issue. I forgot there was an issue for that.

2020-12-30 00:22 UTC, merged

2020-12-30 00:23 UTC, Max094Reikeb commented
Why did you merge it already? I'm the only one who reviewed, you should have wait for a second review...

2020-12-30 00:24 UTC, Goldorion commented
> 
> 
> Why did you merge it already? I'm the only one who reviewed, you should have wait for a second review...

NOYB and SomeoneElse reviewed the PR and everything they asked have been fixed, so I thought it was ready to be merged.

2020-12-30 00:26 UTC, Max094Reikeb commented
Anyways, it's too late now. If @NOYBss or @AlsoSomeoneElse see any problems, they can always do a fixing PR or report a bug.

2020-12-30 00:29 UTC, Goldorion commented
> 
> 
> Anyways, it's too late now. If @NOYBss or @AlsoSomeoneElse see any problems, they can always do a fixing PR or report a bug.

Yeah and the PR doesn't change something, so it can't break workspaces.