Reload plugins button
Team-MCToolkit/MCToolkit pull request #203
Opened 2020-12-30 05:50 UTC by Goldorion

This PR adds a new button (in the "File" section) to reload plugins. As it should not be used by regular users (otherwise, why Klemen didn't add this feature sooner), I added a dialog box to confirm saying it should not be used. I also added a new preference entry to enable developer features and when this preference is not enabled, the button won't be added.

Note: If localizations are changed, the current tab has to be re-opened to use the new translations.

I know this feature can seem to be useless, but I'm bored to always have to re-run MCreator every time I have to change one small thing in a file of plugin. It will save a lot of time for the development.

2020-12-30 14:40 UTC, NOYBss approved these changes
No need to restart the whole program to test the smallest change you make in your plugin? I'm in.

2020-12-30 20:26 UTC, willpill commented
i have a better idea of the dialogue
Enable pref option:
Enable developer features?
Developer Features are best for those who want to develop for MCToolkit, and not regular mod creators. USING developer FEATURES PUTS ALL YOUR WORKSPACES IN RISK. You acknowledge that MCToolkit is NOT RESPONSIBLE FOR ANY WORKSPACE DATA LOSS caused by developer features.

Reload plugin/any developer feature dialogue: 
Reload Plugins?/any other action?
This is a developer feature. It is best for those who want to develop for MCToolkit, and not regular mod creators. You have developer features enabled and you have acknowledged the risks.

2020-12-30 21:38 UTC, Goldorion commented
> 
> 
> i have a better idea of the dialogue
> Enable pref option:
> Enable developer features?
> Developer Features are best for those who want to develop for MCToolkit, and not regular mod creators. USING developer FEATURES PUTS ALL YOUR WORKSPACES IN RISK. You acknowledge that MCToolkit is NOT RESPONSIBLE FOR ANY WORKSPACE DATA LOSS caused by developer features.
> 
> Reload plugin/any developer feature dialogue:
> Reload Plugins?/any other action?
> This is a developer feature. It is best for those who want to develop for MCToolkit, and not regular mod creators. You have developer features enabled and you have acknowledged the risks.

I will make that as soon as I have the motivation. XD

2020-12-31 01:43 UTC, willpill commented
you can just copy and paste this new dialogue to the code?
> 
> > 
> 
> > i have a better idea of the dialogue
> 
> > Enable pref option:
> 
> > Enable developer features?
> 
> > Developer Features are best for those who want to develop for MCToolkit, and not regular mod creators. USING developer FEATURES PUTS ALL YOUR WORKSPACES IN RISK. You acknowledge that MCToolkit is NOT RESPONSIBLE FOR ANY WORKSPACE DATA LOSS caused by developer features.
> 
> > 
> 
> > Reload plugin/any developer feature dialogue:
> 
> > Reload Plugins?/any other action?
> 
> > This is a developer feature. It is best for those who want to develop for MCToolkit, and not regular mod creators. You have developer features enabled and you have acknowledged the risks.
> 
> 
> 
> I will make that as soon as I have the motivation. XD

2021-01-02 13:11 UTC, Max094Reikeb requested changes
It seems some stuff doesn't work.
I enable developpers features as you can see here
<img width="803" alt="Capture d’écran 2021-01-02 à 14 10 02" src="https://user-images.githubusercontent.com/49318596/103458021-62ef7400-4d04-11eb-9b5d-9b2472f2f1d9.png">
But in the file tab, I can't see the button to reload plugins
<img width="288" alt="Capture d’écran 2021-01-02 à 14 10 22" src="https://user-images.githubusercontent.com/49318596/103458024-713d9000-4d04-11eb-8eec-571b92875ed1.png">

2021-01-02 14:52 UTC, Goldorion commented
> 
> 
> It seems some stuff doesn't work.
> I enable developpers features as you can see here
> <img alt="Capture d’écran 2021-01-02 à 14 10 02" width="803" src="https://user-images.githubusercontent.com/49318596/103458021-62ef7400-4d04-11eb-9b5d-9b2472f2f1d9.png">
> But in the file tab, I can't see the button to reload plugins
> <img alt="Capture d’écran 2021-01-02 à 14 10 22" width="288" src="https://user-images.githubusercontent.com/49318596/103458024-713d9000-4d04-11eb-8eec-571b92875ed1.png">

Did you try to close and re-open your workspace? For a few things like this and the localizations workspace needs to be re-open.

2021-01-02 14:59 UTC, Max094Reikeb commented
> Did you try to close and re-open your workspace? For a few things like this and the localizations workspace needs to be re-open.

Indeed it works after that.

2021-01-02 15:00 UTC, Max094Reikeb approved these changes
Sounds good.

2021-01-02 15:05 UTC, merged

2021-01-02 15:15 UTC, Goldorion commented
> 
> 
> Sounds good.

Why did you merge this PR? I still had to change and add some texts.

2021-01-02 15:16 UTC, Max094Reikeb commented
> > Sounds good.
> 
> Why did you merge this PR? I still had to change and add some texts.

OOOps sorry... Why didn't you put it into draft? We should have a new label for when a PR is not ready to be merged...
Open a new one with your changes then.