New blockbase (Hopper)
Team-MCToolkit/MCToolkit pull request #210
Opened 2021-01-03 00:52 UTC by Max094Reikeb

This PR adds a Hopper blockbase.
Closes #62

2021-01-03 01:02 UTC, Goldorion reviewed
Why do you add new procedure blocks?

2021-01-03 01:04 UTC, Max094Reikeb commented
> Why do you add new procedure blocks?

I don't? Where do I add procedure blocks?

2021-01-03 01:16 UTC, Goldorion requested changes
You forgot the code in the two code template files. You have to add a line for the "extends ..." and another one for the "super(..." (the content of the "super" depends on the block base).

2021-01-03 01:50 UTC, Goldorion requested changes
You forgot the lines to extend the Hopper class.

2021-01-03 01:51 UTC, Max094Reikeb commented
> You forgot the lines to extend the Hopper class.

How do I do that?

2021-01-20 18:52 UTC, Goldorion commented on plugins/generator-1.16.4/forge-1.16.4/templates/block.java.ftl
> +		</#if>
What's the purpose of this </#if>?
It seems this line cause a build error.

2021-01-20 20:11 UTC, Max094Reikeb commented on plugins/generator-1.16.4/forge-1.16.4/templates/block.java.ftl
> +		</#if>
Fixed.

2021-01-23 18:15 UTC, Goldorion requested changes
I tested in-game (1.15.2 only), and I noticed a few things.
1. Custom hoppers can not send items to another hopper (the same custom hopper) or to a Vanilla hopper.
2. If we enable the tile entity with the Hopper block base, the block doesn't act as a hopper. So you should not enable this option when the Hopper block base is selected.
3. The item entity when dropped doesn't have the same size as other item entities. (Example on the screenshot below)
4. When the hopper contains an item, it can't contain another type of item (e.g. if it has a diamond, it won't accept a gold ingot). To accept another type of item, we need to replace the hopper.
5. When the player has the custom hopper in his hand, the 3D model is used instead of the item texture (Vanilla hopper doesn't use the 3D mode).
![2021-01-23_13 07 53](https://user-images.githubusercontent.com/38427877/105610282-f1dc3300-5d7c-11eb-9970-0d9dde4c484a.png)

I put this PR as a draft, so it will give you the time to fix these problems.

2021-06-25 14:22 UTC, closed without merging